const USERS_PER_PAGE=5
const PRODUCT_PER_PAGE = 5
const CATEGORY_PER_PAGE = 10
const ITEMS_PER_PAGE = 6
const BRAND_PER_PAGE=10
const ORDER_PER_PAGE = 8
const SALES_PER_PAGE = 10
const NEW_PRODUCTS_PER_PAGE = 3
module.exports = {
    USERS_PER_PAGE,
    PRODUCT_PER_PAGE,
    CATEGORY_PER_PAGE,
    ITEMS_PER_PAGE,
    BRAND_PER_PAGE,
    ORDER_PER_PAGE,
    SALES_PER_PAGE,
    NEW_PRODUCTS_PER_PAGE
}