const USERS_PER_PAGE=4
const PRODUCT_PER_PAGE = 4
const CATEGORY_PER_PAGE = 2
const ITEMS_PER_PAGE = 3
const BRAND_PER_PAGE=6
const ORDER_PER_PAGE = 2
module.exports = {
    USERS_PER_PAGE,
    PRODUCT_PER_PAGE,
    CATEGORY_PER_PAGE,
    ITEMS_PER_PAGE,
    BRAND_PER_PAGE,
    ORDER_PER_PAGE
}